name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build
    - name: Run linter
      run: cargo clippy --tests --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test
